pipeline{
    agent any

    stages{
        stage("A"){
            steps{
                echo "========executing A========"
                sh 'ls -ll'
                sh 'docker-compose --version'
                dir('Devops') {
                    sh 'docker-compose up pro'
                    //sh 'docker build -f flask.Dockerfile -t pro Providers'
                }
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}